site_name: tinyMLx Docs
site_url: "https://iamprasadraju.github.io/tinyMLx/"
repo_url: https://github.com/iamprasadraju/tinymlx.git
edit_uri: edit/main/docs/

theme:
  name: material
  logo: tinymlx-light.svg
  favicon: tinymlx-light.svg
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Philosophy: philosophy.md
  - API Reference:
    - LinearModels:
      - LinearRegression: api/linear_regression.md
      - LogisticRegression: api/logistic_regression.md
    - Loss Functions:
      - AbsoluteError: api/absolute_error.md
      - SquaredError: api/squared_error.md
  - Theory:
    - Calculus Mapping: theory/calculus_mapping.md
  - Recipes:
    - Manual Gradient Descent: recipes/manual_gradient_descent.md