[project]
name = "trueml"
version = "0.0.1"
description = "Machine learning without hidden abstractions."
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"

authors = [
    { name = "Prasad Raju G" }
]


classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    "numpy"
]

[project.urls]
Homepage = "https://github.com/iamprasadraju/trueml"
Repository = "https://github.com/iamprasadraju/trueml"
Documentation = "https://iamprasadraju.github.io/trueml/"
Issues = "https://github.com/iamprasadraju/trueml/issues"


[project.optional-dependencies]
dev = [
    "pytest>=9.1.0",
    "ruff>=0.15.17",
    "pre-commit>=4.6.0",
    "black>=25.9.0",
    "isort>=6.1.0",
]

docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]


[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["."]
