[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "trueml"
version = "0.0.1"
description = "Machine learning without hidden abstractions."
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"

authors = [
    { name = "Prasad Raju G", email = "gls.prasadraju@gmail.com" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "numpy",
]

[project.optional-dependencies]
viz = [
    "matplotlib",
]

[project.urls]
Homepage = "https://github.com/iamprasadraju/trueml"
Repository = "https://github.com/iamprasadraju/trueml"
Documentation = "https://iamprasadraju.github.io/trueml/"
Issues = "https://github.com/iamprasadraju/trueml/issues"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "prek>=0.4.12",
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]

docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
